### ISSUE TITLE
作业问题

### ISSUE THREAD

**Issue by miniflycn** [FE-star/exercise1#16]
* 捕获抛错不要傻傻的用try，这样错误提示其实不够友好
* 抛出错误需要校验
* 注意学习下`.gitignore`文件的使用

**Comment by aoxiaoqiang** [comment]
使用 [assert.throws(block[, error][, message])](http://nodejs.cn/api/assert.html#assert_assert_throws_block_error_message) 来捕获 fn 的错误吧
