### ISSUE TITLE
github action 的友情提醒

### ISSUE THREAD

**Issue by shenxiang11** [FE-star/exercise1#220]
jest --watchAll

如果跑 github actions，记得把 --watchAll 去掉，否则跑不完～

**Comment by miniflycn** [comment]
~~呃，我忘记了。。。

**Comment by sxyuzhenhua** [comment]
--watchAll, 没明白加这个，在哪里重复跑了，影响了啥

**Comment by miniflycn** [comment]
> 

可以看看package.json的scripts里面的test：jest --watchAll。
所以CI在运行yarn test的时候是watch模式运行jest，这样会导致测试用例一直卡在那里，不会终止。
